// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALn4x-q6NGzfOHBTjzjW7hIRDrYNG4d8o',
    appId: '1:389586873439:web:YOUR_WEB_APP_ID',
    messagingSenderId: '389586873439',
    projectId: 'otp-socorre',
    authDomain: 'otp-socorre.firebaseapp.com',
    storageBucket: 'otp-socorre.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALn4x-q6NGzfOHBTjzjW7hIRDrYNG4d8o',
    appId: '1:389586873439:android:d42ffad34e45eae6073fea',
    messagingSenderId: '389586873439',
    projectId: 'otp-socorre',
    storageBucket: 'otp-socorre.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJzAuOgIUI7zGaW_viQUr0GqQuEY1l2po',
    appId: '1:389586873439:ios:f45a756a7dfb8460073fea',
    messagingSenderId: '389586873439',
    projectId: 'otp-socorre',
    storageBucket: 'otp-socorre.firebasestorage.app',
    iosBundleId: 'com.socorreai.partner.socorre-ai-partner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJzAuOgIUI7zGaW_viQUr0GqQuEY1l2po',
    appId: '1:389586873439:ios:f45a756a7dfb8460073fea',
    messagingSenderId: '389586873439',
    projectId: 'otp-socorre',
    storageBucket: 'otp-socorre.firebasestorage.app',
    iosBundleId: 'com.socorreai.partner.socorre-ai-partner',
  );
}
