'use strict';

const COMMERCE_TYPES = Object.freeze({
  DIGITAL_GOOD: 'DIGITAL_GOOD',
  DIGITAL_SUBSCRIPTION: 'DIGITAL_SUBSCRIPTION',
  PHYSICAL_GOOD: 'PHYSICAL_GOOD',
  REAL_WORLD_SERVICE: 'REAL_WORLD_SERVICE',
});

const SALES_CHANNELS = Object.freeze({
  IOS_APP: 'IOS_APP',
  ANDROID_APP: 'ANDROID_APP',
  WEB: 'WEB',
});

const PAYMENT_METHODS = Object.freeze({
  CASH: 'CASH',
  CARD: 'CARD',
  PIX: 'PIX',
  STORE_BILLING: 'STORE_BILLING',
});

const PAYMENT_PROCESSORS = Object.freeze({
  INTERNAL_CASH: 'INTERNAL_CASH',
  STRIPE: 'STRIPE',
  APPLE_APP_STORE: 'APPLE_APP_STORE',
  GOOGLE_PLAY: 'GOOGLE_PLAY',
});

const PAYMENT_STATUSES = Object.freeze({
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  PAID: 'PAID',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
});

const PAYMENT_ATTEMPT_STATUSES = Object.freeze({
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  SUCCEEDED: 'SUCCEEDED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
});

module.exports = {
  COMMERCE_TYPES,
  SALES_CHANNELS,
  PAYMENT_METHODS,
  PAYMENT_PROCESSORS,
  PAYMENT_STATUSES,
  PAYMENT_ATTEMPT_STATUSES,
};
